# Site settings
author: Anthony Romagnolo
title: Journey through Coding
header-img: img/home-bg.png
email: anthonyroma741@gmail.com
copyright_name: Anthony Romagnolo
description: > # this means to ignore newlines until "baseurl:"
  The Romo life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  antromo741

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
